### PR TITLE
Tentative schedule for talks.

### PR DESCRIPTION
**Pull request by ArchRobison**
This PR adds the tentative schedule for talks.  It also indicate which workshops are in morning or afternoon.

**Do we have confirmation** from Guy Steele and TIm Holy on which days they are talking?

Abstracts reordered to be consistent with schedule.  Unfortunately the current `gen.jl` interleaves them in the two-track situation.  Fixing that can wait for another day.

### CODE REVIEW

**Comment by ArchRobison** [comment]
[Speakers confirmed](https://github.com/JuliaCon/JuliaCon2016/issues/53#issuecomment-223987393).  Can someone give this PR a final look, or at least a second opinion?

**Comment by ViralBShah** [comment]
I am looking at this right now and have some thoughts.

**Comment by ViralBShah** [comment]
On opening day, I think we should not do juliabox after the keynote. That update is much smaller. I think we should have a debugger session by Keno right after the keynote. On Thursday, instead of Minecraft and Raspberry Pi, we should do Juno.

Is something messed up for Friday 10:40?

We also need sponsor slots and gsoc - unless I missed that in my scan and search.

**Comment by ViralBShah** [comment]
Ok - I see Friday 10:40 is the gsoc session in parallel with a full talk.

**Comment by ViralBShah** [comment]
I think DSGE.jl should not follow Sargent as they are similar. DSGE.jl could go into a track, and we could have something of wider interest in the common session.

**Comment by ViralBShah** [comment]
I think Julia and R by Doug Bates would be a good one after Sargent on Friday, potentially.

What would be the right thing to do - I am happy to edit this schedule? Should I use the script which I read about somewhere?

**Comment by ArchRobison** [comment]
I've been using Excel on a color-coded sheet.  Let's see if I can upload it to Google sheets and share it.  I've been counting (T) as 37.5 minutes and (L) as 12.5 minutes, to allow padding and give a 1:3 exchange ratio.

I put`DSGE.jl` after Sargent's talk precisely because it is related , and I've already checked with the speaker that the slot work for her.  That talk was also the one we promoted from a lightning talk.

I forgot to include Keno because his talk has never been formally added to a list.

The program committee specifically called out 4 talks for single-tracking:
* Raspberry Pi
* DataScience
* Teaching Julia
* JuliaBox

**Comment by ArchRobison** [comment]
I've put the color-coded sheet [here](https://docs.google.com/spreadsheets/d/1QuDAY_Gl9HwLUVWcl_3v-u9p-gGJYTjA5jPIOtj6CD0/edit?usp=sharing).  Anyone with the link should be able to edit it.  Cells with the same color were candidates for going in the same session.

**Comment by ViralBShah** [comment]
I do think that it is better to have the debugger single tracked as well. On the others, I will go with the committee's decision, since I was not on all the calls. It would be good for JuliaBox to be single tracked if we can accommodate the debugger as well.

**Comment by ArchRobison** [comment]
I should clarify: feel free to edit the google sheet and then we can push it back into the `schedule.csv`.  

We're only going 8:45--17:05.  Consider lengthening the day slightly if that helps.

**Comment by ViralBShah** [comment]
On Keno, I don't think he knows he's talking either - but I'm email him that he is.

**Comment by ViralBShah** [comment]
There's one more single track talk I would like to propose - a roadmap to 1.0 - @StefanKarpinski either by himself or with others. We will need to lengthen the day. I am working on slight tweaks to the schedule and seeing how it fits.

**Comment by ninjin** [comment]
Overall, the schedule looks great and I agree with the decisions about what to highlight.  Thanks a ton for helping with this @ArchRobison.

Minor comments:
* Yeppp! just asked to have their talk on Friday and we already scheduled them on Friday without knowing about this.  Just adding this as a comment if we consider moving that block.
* Is the Julia India talk of a wide enough interest to "deserve" to be in the single track?

**Comment by ninjin** [comment]
@ViralBShah: I agree that the roadmap etc. would be desirable, any ETA on when you could have this ironed out since we are running late and are pretty much ready to go with the schedule.

**Comment by ViralBShah** [comment]
I think Julia India does not need to be single track, and we have other things like Roadmap and Debugger we want in the single track.

**Comment by ArchRobison** [comment]
@ViralBShah : Are you going to edit [the schedule sheet](https://docs.google.com/spreadsheets/d/1QuDAY_Gl9HwLUVWcl_3v-u9p-gGJYTjA5jPIOtj6CD0/edit?usp=sharing)?

**Comment by ViralBShah** [comment]
I'm on it now.

**Comment by ViralBShah** [comment]
Is 10:10 - 10:40 a break? 12-1:30pm is lunch. Are there other breaks?

**Comment by ArchRobison** [comment]
Yes, those are breaks.  There's also a break in the afternoon.

**Comment by ViralBShah** [comment]
If you see my updated one now, I have Gallium and Julia 1.0 in as full talks. That essentially is making it difficult to incorporate JuliaBox(L) and Raspberry Pi(T), both of which are deserving single track.

**Comment by ViralBShah** [comment]
Hold on. One more round of changes. Perhaps Jameson's stuff while really interesting may be too much about internals.

**Comment by ViralBShah** [comment]
Ok, I moved Jameson's talk to be in parallel with the GSOC talks. The other option to retain it in single track is to start 15 mins earlier and have lunch a little later on the third day, so that Jameson can speak after Erica.

**Comment by ViralBShah** [comment]
Now making space for sponsors.

**Comment by ViralBShah** [comment]
Is this ok to go with?

**Comment by ninjin** [comment]
I have looked through it and I think it looks excellent.

**Comment by ArchRobison** [comment]
What does the key `Gallium` denote?  Is there a title or abstract for it?

**Comment by ArchRobison** [comment]
`Gallium` is Keno's talk, right?  Can I list him as the presenter?

**Comment by ArchRobison** [comment]
To make reviewing easier, I've put a tar file with the fine `_site` files [here](https://drive.google.com/file/d/0B2kelDtRe-dqR2VTTXFDN2VpTFk/view?usp=sharing).  Unpack it with `tar xvfz _site.tgz` and start at `index.html` and see if the link to `schedule.html` works, and that the links there work in turn.

There may be some UTF8 nits related to my Jekyll installation.  These seem to go away at the JuliaCon site.

**Comment by ViralBShah** [comment]
Yes, Gallium is keno's talk on the debugger.

**Comment by ViralBShah** [comment]
I checked out the branch and ran jekyll. Looks good enough to publish for now. Will keep getting tweaked and updated.

**Pull request merged**
