### PR TITLE
Mode 2015 website to 2015 folder and add 2016 site with venue and committee info

### PR DESCRIPTION
**Pull request by andreasnoack**
We have already received the first question about date and venue for JuliaCon 2016 so I've made a new website with that information as well as contact info. The 2015 site is moved to the 2015 folder and I've added a link to it in top of the 2016 site.

@IainNZ Do you know how/if the Google Analytics stuff should be updated?

### CODE REVIEW

**Comment by IainNZ** [comment]
It should be fine, it just lives in the header and its still there.

**Comment by andreasnoack** [comment]
Will we be able to track the visits to the 2015 and 2016 sites separately?

**Comment by IainNZ** [comment]
Well as people visit the new seperate 2015 pages they'll get a new count. There will only ever be one "history" for /index.html

**Comment by StefanKarpinski** [comment]
I suggested long ago and still think we should do this: make `juliacon.org/index.html` be a redirect to `juliacon.org/2016/` (ideally an HTTP 307 if we can do that, but 302/303 would also do the trick). This way no pages ever change URLs, which is shitty and breaks the way the Internet is supposed to work, and in as a pure matter of self-interest makes it hard for us to track visits to the pages for the different years separately.

**Comment by IainNZ** [comment]
How do we do that without control of the server?

**Comment by StefanKarpinski** [comment]
HTML redirect: http://stackoverflow.com/a/5411601/659248.

**Comment by ArchRobison** [comment]
+1 for the redirect.  I've been some redirects on my old personal site for years.  (e.g. http://home.comcast.net/~arch.robison/frequon.html redirects to my new site.)

**Comment by StefanKarpinski** [comment]
For example, I used an HTML redirect for the [license page](https://github.com/JuliaLang/julialang.github.com/blob/master/license/index.html).

**Comment by andreasnoack** [comment]
@StefanKarpinski I'm fine with that solution and will see if I can manage to make that change.

**Comment by StefanKarpinski** [comment]
Sure, I would do it, but I don't want to start making conflicting changes and I'm not super familiar with the setup of the juliacon.org site.

**Comment by andreasnoack** [comment]
Can each subfolder be loaded as an independent Jekyll site? It would be nice to have all content of a JuliaCon site in one folder, but it seems that the `_layouts` folder has to be at the root level of the site. If I copy the `_layouts` folder to `2015` then I have to `jekyll serve` inside the `2015` folder. How will `github.com` handle this?

**Comment by IainNZ** [comment]
It'll do it from root. You could Jekyll build it locally and check in the built plain html version of 2015

**Comment by StefanKarpinski** [comment]
You could have a different layout for each year and just copy the previous year's layout file when we make a new site for a new year.

**Comment by StefanKarpinski** [comment]
> It'll do it from root. You could Jekyll build it locally and check in the built plain html version of 2015

Or that. Probably easier since we won't really want to be updating old versions anyway.

**Comment by andreasnoack** [comment]
Okay. I've tried to reorganize the sites into separate folders including the site for 2016. The good thing is that it keeps the sites nicely separated. The downside is that we'll have to run `jekyll build --source 2016src --destination 2016` each time we update the site which requires that those who update the site have Jekyll installed.

**Comment by StefanKarpinski** [comment]
Can we somehow use automatic rendering for the current site but not for the old ones?

**Comment by andreasnoack** [comment]
I guess that is close to the solution I had in the first commit. I agree that it is better. We'll have to make many updates to the site so it is probably good if the rendering is automated.

**Comment by andreasnoack** [comment]
The redirect is now gone in favor of developing the present site in the root folder such that it is rendered automatically. We can revisit this later if necessary, but I think we should get the new site the the dates and location up today.

**Comment by ninjin** [comment]
Excellent!

**Pull request merged**
