### PR TITLE
Add more times to schedule + small tweaks

### PR DESCRIPTION
**Pull request by ArchRobison**
* Add more times to schedule.
* Add "high voltage" symbols to lightning talks.
* Swap India/BoundedIntegers talks within their session.
* Swap Intel/Moore slots.

### CODE REVIEW

**Comment by ArchRobison** [comment]
FYI, I also added Lars Ruthotto's lightning talk.

**Comment by ViralBShah** [comment]
I have a request for a lightning talk from NAG. Actually, it is Reid Atchinson, who presented at the first JuliaCon and is now at NAG.

I made no promises, but I think if we have a 10 min slot or if someone cancels, we should try and fit them in. Is it possible?

**Comment by ArchRobison** [comment]
Status of this PR: Current set of pending commits reflects all requested changes *except* NAG.  NAG could go in slot concurrent with "Building the Julia community in India" if others are okay with that.

**Comment by ArchRobison** [comment]
Does Reid Atchinson have a title/abstract for his talk?  With the Rata cancellation, we could put him in my former slot.

**Comment by ninjin** [comment]
@ViralBShah: Did Reid send a title and abstract to you?

**Pull request merged**
