### PR TITLE
Add first two keynote speakers to website

### PR DESCRIPTION
**Pull request by vchuravy**

### CODE REVIEW

**Comment by vchuravy** [comment]
Note to self, do not merge until list is completely finalized.

**Comment by aviks** [comment]
Maybe this should also wait for the new website design that Adrian is working towards?

**Comment by essenciary** [comment]
Begun working on restyling to the home page. Design work continues for the rest of the pages (most importantly, the speakers pages). 
Might need to setup some staging hosting (need to look into dev/staging setup so collaborators can join).

**Comment by jpfairbanks** [comment]
It looks like this material needs to go in includes/content.html or includes/keynote-speaker.html

**Comment by essenciary** [comment]
@jpfairbanks We agreed not to publish this until we have the full list. Also see the comment by @vchuravy on Nov 21st.

**Pull request closed without merging**
