### PR TITLE
Rough cut of schedule

### PR DESCRIPTION
**Pull request by IainNZ**
Simple page, separated in 3 sections, talks in alphabetical order by title. Links from main page. Can go back later and add hyperlinks if we want but I figured getting it up is first priority

### CODE REVIEW

**Comment by IainNZ** [comment]
Think I got them all now, generated this from the Google Doc. I can push more improvements directly as I get time.

**Comment by ArchRobison** [comment]
I suggest moving Sanders' workshop to its own **Special Workshop (Wednesday)** category heading to make it clearer that it is the odd duck.  Then the Workshops heading could be changed to **Workshops (Saturday)**.

**Comment by ArchRobison** [comment]
Or simpler headings: **Workshop (Wednesday)** and **Workshops (Saturday)**.

**Comment by IainNZ** [comment]
I put day subheaders, looks pretty clean

**Comment by ArchRobison** [comment]
The `<br>` just before the `<h3>Saturday` was causing a large vertical gap (larger than any other vertical gap) on the page, using Chrome or IE11.  Other than that, it looks good to me.

**Comment by IainNZ** [comment]
Ok, fixed.

**Pull request merged**
