### PR TITLE
Add abstracts + bios for talks.

### PR DESCRIPTION
**Pull request by ArchRobison**
This PR adds a page with abstracts/bios for the regular and lightning talks.  They are in the same order as the schedule.  This PR also adds Art Diky's talk.

### CODE REVIEW

**Comment by IainNZ** [comment]
Fantastic! Let me pull this down and have a quick look, but otherwise I think we are good to go

**Comment by IainNZ** [comment]
Maybe under the word "Schedule" we could add something like? To make it very obvious.
```
<p>Click the dates to see talk abstracts and speaker biographies.</p>
```

**Comment by ArchRobison** [comment]
Excellent suggestion.  Now incorporated (for workshops too.)  Please give revision a quick review, and if it looks good, I'll merge the PR.

**Comment by IainNZ** [comment]
:+1:

**Comment by IainNZ** [comment]
I'm going to steal your thunder here

**Comment by ArchRobison** [comment]
Thanks.

**Pull request merged**
